repos:
-   repo: local
    hooks:
    -   id: flake8
        name: Flake8
        description: This hook runs flake8 within the project pipenv environment.
        entry: pipenv run lint
        language: python
        types: [python]
        require_serial: true
